language: python
python:
# - "2.6"    # Some unit tests don't pass, but everything seems to work
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"
# - "pypy"   # Some unit tests don't pass, but everything seems to work

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytz tzlocal

# command to run tests
script:
  - python -m pytest -v
